# Generated by Django 3.1.4 on 2020-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.CharField(max_length=8)),
                ('ort', models.CharField(max_length=35)),
                ('landkreis', models.CharField(max_length=45)),
                ('bundesland', models.CharField(max_length=25)),
            ],
        ),
    ]
