# Generated by Django 3.1.4 on 2020-12-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0002_auto_20201210_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locus',
            options={'ordering': ['bundesland', 'ort']},
        ),
    ]
